new registryMetals("aeonsteel", 0x42b983)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("aeroite", 0x04e6ff)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("aqualite", 0x1de9b6)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("asgardium", 0xffcd26)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("astral_metal", 0xe040fb)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("chromasteel", 0x9128c6)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("chromium", 0x80deea)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("cosmilite", 0xff503e)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("crimsonite", 0xef5350)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("cryonium", 0xb2affe)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("cytosinite", 0xb0ed4e)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("durasteel", 0x2d45d5)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("electronium", 0x5243ce)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("infernium", 0xf7811c)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("knowledge_essence", 0x6ae503)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("manganese_iron", 0x455a64)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("manganese_steel", 0x616161)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("protonium", 0xe140fa)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("shadowium", 0x8f2ba0)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()

new registryMetals("stainless_steel", 0x787878)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("terra_alloy", 0x9f650c)
    .dust()
    .rod()
    .gear()
    .ingot()
    .nugget()
    .plate()

new registryMetals("titanium", 0xd8d8d8)
    .dust()
    .rod()
    .gear()
    .dirtyDust()
    .clump()
    .crystal()
    .shard()
    .ingot()
    .nugget()
    .rawOre()
    .plate()